### ISSUE TITLE
Security : restrict access on customer controller

### ISSUE THREAD

**Issue by camille-guerber** [Liotey/technical-test#1]
It's possible to access all the controller's routes directly via the url without being connected

**Comment by Tilotiti** [comment]
Bonjour Camille !
Je vois que tu as commencé à travailler sur ce projet et je t'en remercie !

Tu pourrais penser à forker le repository plutôt que d'écrire dessus ? Comme ça, tes tickets et tes modifications sont sur le tiens et c'est bien plus pratique ;)

Merci beaucoup ! Et bonne journée :)

**Comment by camille-guerber** [comment]
Bonjour,

Effectivement, petite erreur de ma part je corrige cela as soon as possible et continue de travailler dessus. Je vous tiens au courant de mon avancée.

En vous souhaitant une bonne journée,

Bien cordialement
